### ISSUE TITLE
Sphinx External TOC merge into Jupyter Book

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#10]
# Tasks

- [x] Get this PR merged https://github.com/executablebooks/jupyter-book/pull/1293
- [x] Add documentation for the new TOC structure: https://github.com/executablebooks/jupyter-book/pull/1321
- [x] Finish up https://github.com/executablebooks/jupyter-book/issues/1323
- [x] Release Jupyter Book

**Comment by choldgraf** [comment]
This is done!
