### ISSUE TITLE
Automate building and pushing images for users with repo2docker action

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/external#11]
Users should ideally have full control over the images their hub runs. Setting up GitHub repositories with automatic building via GitHub actions + [repo2docker-action](https://github.com/jupyterhub/repo2docker-action) is the best way to do this. It sticks to standards, plus people can test out their image on mybinder.org!

We need a couple new features in repo2docker-action for this to fully work.

- [ ] Support for pushing to repositories without username / password (like ECR) https://github.com/jupyterhub/repo2docker-action/issues/65
- [ ] Document how to set this up for various registries https://github.com/jupyterhub/repo2docker-action/issues/61
- [ ] Support pushing to multiple registries https://github.com/jupyterhub/repo2docker-action/issues/70
