### ISSUE TITLE
Create a roadmap and plan for the Pangeo collaboration

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#6]
# Background

We are ramping up the collaboration with the Pangeo project via a sub-award from @rabernat. As a first step, we'll need to define a plan for things to prioritize and work towards. This is an issue to track the process.

Some things we'll need to answer:

- [ ] Where will we keep a roadmap / high-level plan?
- [ ] Where will we track deliverables?
- [ ] What should be our high-level goals to work towards?
- [ ] What deliverables should we put on our roadmap, and prioritize first?
- [ ] How will we coordinate with the broader Pangeo community?
- [ ] Where will the information for the above items be stored?

# Important information

- [Here's a Discussion to discuss some ideas for technical things to work towards](https://github.com/2i2c-org/team-compass/discussions/90)

# Tasks to complete

- [ ] https://github.com/2i2c-org/pilot-hubs/issues/482
- [ ] Once that's done, begin answering the questions above
- [ ] Loop in Jim CH to the Pangeo meeting to get his perspective on new development opportunities in Dask / Dask Gateway
