### ISSUE TITLE
Coordination plan and roadmap for new contracts on the EBP

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#7]
# Background

We are ramping up some work on the Executable Books Project, in partnership with @damianavila and @rowanc1. As we get started, it'll be helpful for us to plan out some structure for how we'd like to work together, and what to work on.

Some things to decide on:

- [ ] Where will we keep a roadmap / high-level plan?
- [ ] Where will we track deliverables?
- [ ] What should be our high-level goals to work towards?
- [ ] What deliverables should we put on our roadmap, and prioritize first?
- [ ] How will we coordinate with the broader EBP community?
- [ ] Where will the information for the above items be stored?

# Important information

- [Here is the deliverables that we wrote into the Statement of Work for Curvenote](https://docs.google.com/document/d/1BrJ3_USeE5OkL5Ia7S8eRBhULiq4RmIh_2PZY432KWk/edit#)

# Tasks

- [x] Get @damianavila onboarded
- [x] Get @rowanc1 onboarded
- [x] Have some discussion in this issue about answering some of these questions
- [ ] Plan a meeting between the three of us at least, to do some initial planning and conversation

# Resolution

see: https://github.com/2i2c-org/upstream/issues/7#issuecomment-911942960

**Comment by damianavila** [comment]
@choldgraf can you give us access to that google document when you have some time? Thanks!

**Comment by choldgraf** [comment]
@damianavila Added your 2i2c account!

**Comment by choldgraf** [comment]
After a few rounds of discussion with folks, I think that we've decided to use the following approach for this collaboration:

- We'll track deliverables and issues in the upstream repository, that way we do not split discussion/planning between EBP and 2i2c communities.
- If there is a specific EBP thing we wish to accomplish, we can track it in 2i2c via "tracking issues" in this upstream repository
- For medium-term planning, we don't have a clear story yet, but on the 2i2c side we seem to be coalescing around "Project Boards" to track medium-term deliverables, and I think that this is where EBP is headed as well (at least on Thebe we've had suggestions to add to a project board there). We also have a board on the pydata them for that related upstream work.
  - EBP activity board: https://github.com/orgs/executablebooks/projects/7?fullscreen=true
  - https://github.com/pydata/pydata-sphinx-theme/projects/1
- We'll coordinate synchronously via the monthly EBP team meetings, and via off-cycle meetings with the CurveNote team. Damian and I will coordinate via our regular 2i2c meetings.

gonna close this one as I think the major pieces are there, and we can iterate as we continue the collaboration
