### ISSUE TITLE
Submit an application for the CZI EOSS grant around the "Community Developer" role

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/external#8]
Issue: https://github.com/jupyterhub/team-compass/issues/402
Proposal: https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit#heading=h.6xl5ernp7921

# Tasks

- [x] Improve the work plan
- [x] Improve the Milestones
- [x] Improve the Expected Outcomes
- [x] Improve the Evaluation and Learning Goals
- [x] Share copy of the proposal
- [x] Tell the team
